[[plugins]]
repo = 'Shougo/dein.vim'

[[plugins]]
repo = 'Shougo/vimproc.vim'
build = 'make'

[[plugins]]
repo = 'vim-jp/vimdoc-ja'

[[plugins]]
repo = 'w0ng/vim-hybrid'

[[plugins]]
repo = 'itchyny/lightline.vim'

[[plugins]]
repo = 'cohama/lexima.vim'

[[plugins]]
repo = 'airblade/vim-gitgutter'

[[plugins]]
repo = 'osyo-manga/vim-anzu'

[[plugins]]
repo = 'thinca/vim-quickrun'

[[plugins]]
repo = 'cocopon/iceberg.vim'

[[plugins]]
repo = 'haya14busa/is.vim'

[[plugins]]
repo = 'lambdalisue/gina.vim'

[[plugins]]
repo = 'mhinz/vim-startify'

[[plugins]]
repo = 'tyru/caw.vim'

# [[plugins]]
# repo = 'markonm/traces.vim'

[[plugins]]
repo = 'prabirshrestha/vim-lsp'

[[plugins]]
repo = 'machakann/vim-sandwich'

[[plugins]]
repo = 'sgur/vim-editorconfig'

[[plugins]]
repo = 'andymass/vim-matchup'

[[plugins]]
repo = 'rhysd/clever-f.vim'

[[plugins]]
repo = 'othree/yajs.vim'

[[plugins]]
repo = 'basyura/twibill.vim'

[[plugins]]
repo = 'jshin/vim-go-syntax'

[[plugins]]
repo = 'ujihisa/neco-look'

[[plugins]]
repo = 'mattn/webapi-vim'

[[plugins]]
repo = 'cespare/vim-toml'

[[plugins]]
repo = 'roxma/nvim-yarp'
if = '''has('python3')'''

[[plugins]]
repo = 'roxma/vim-hug-neovim-rpc'
if = '''has('python3')'''

[[plugins]]
repo = 'Shougo/neosnippet-snippets'
